"""Curated adjective and noun lists for slug generation.

Constraints (enforced by tests in ``tests/unit/test_slug.py``):

- Each word matches ``^[a-z]{3,10}$`` (lowercase ASCII, 3-10 chars).
- Both lists contain ≥ 64 entries (collision space ≥ 64·64·65536 ≈ 268M).
- The two lists are disjoint.
- SFW / non-political / non-offensive.

When adding new words: keep them memorable, pronounceable in English,
and visually distinct. Prefer concrete nouns over abstract; prefer
sensory adjectives over judgemental ones.
"""

from __future__ import annotations

DEFAULT_ADJECTIVES: tuple[str, ...] = (
    "happy",
    "brave",
    "calm",
    "eager",
    "kind",
    "quiet",
    "swift",
    "witty",
    "proud",
    "lucky",
    "shy",
    "bold",
    "bright",
    "clever",
    "curious",
    "daring",
    "gentle",
    "honest",
    "jolly",
    "lively",
    "merry",
    "mighty",
    "neat",
    "nice",
    "noble",
    "peppy",
    "plucky",
    "quick",
    "silly",
    "smart",
    "sunny",
    "tidy",
    "zesty",
    "cosmic",
    "crisp",
    "dusty",
    "fancy",
    "fluffy",
    "fuzzy",
    "glad",
    "golden",
    "grand",
    "green",
    "hollow",
    "icy",
    "jade",
    "keen",
    "lemon",
    "loyal",
    "lunar",
    "misty",
    "murky",
    "polar",
    "royal",
    "rosy",
    "rustic",
    "sleek",
    "solar",
    "spicy",
    "steady",
    "sturdy",
    "vivid",
    "warm",
    "wise",
)

DEFAULT_NOUNS: tuple[str, ...] = (
    "fox",
    "wolf",
    "bear",
    "hawk",
    "tiger",
    "lion",
    "eagle",
    "shark",
    "whale",
    "panda",
    "otter",
    "falcon",
    "rabbit",
    "badger",
    "dolphin",
    "raven",
    "lynx",
    "cheetah",
    "hippo",
    "iguana",
    "jaguar",
    "koala",
    "lemur",
    "mole",
    "narwhal",
    "ocelot",
    "platypus",
    "quokka",
    "robin",
    "seal",
    "turtle",
    "urchin",
    "viper",
    "wombat",
    "yak",
    "zebra",
    "coral",
    "moss",
    "petal",
    "river",
    "forest",
    "canyon",
    "meadow",
    "valley",
    "summit",
    "cloud",
    "comet",
    "galaxy",
    "nebula",
    "aurora",
    "moon",
    "star",
    "planet",
    "beacon",
    "lantern",
    "prism",
    "quartz",
    "ember",
    "orbit",
    "harbor",
    "anchor",
    "kite",
    "meteor",
    "phoenix",
)
